# Continuous integration with travis
language: r
sudo: required



# cache packages to speed up builds
cache: packages

r_packages:
 - covr
 - ggplot2
 - testthat
 - assertthat
 - raster
 - sp 
 - reshape2
 - tidyr
 - cowplot
 - devtools
 
coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 99%  # we always want 80% coverage here
        threshold: 7%
        
after_success:
 - Rscript -e 'library(covr);codecov()'


matrix:
  include:
    - r: release
      r_github_packages: andrewzm/INLA
    - r: devel
      r_github_packages: andrewzm/INLA
    - r: devel
      env: _R_CHECK_FORCE_SUGGESTS_=false
      install: R -e 'install.packages("devtools", dep = TRUE);devtools::install_deps(dep = c("Depends", "Imports"))'




